#!/bin/bash

for d in `ls -d mcts-BH*`;
  do
  cd $d
for c in `ls -d tree-?`;
  do
  cd $c
  for f in `ls *.dot`; 
    do
    dot -Tpng $f -o ${f%\.*}.png
  done
#   for f in `ls full*`; 
#     do
#     dot -Tsvg $f -o ${f%\.*}.svg
#   done
  cd ..
done
  cd ..
done

#   for f in `ls full-tree*`; 
#     do
#     dot -Tsvg $f -o ${f%\.*}.svg
#   done